### ISSUE TITLE
Allow using steampipe to fix things without actually moving data

### ISSUE THREAD

**Issue by Efreak** [DjScribbles/GamePipe#14]
I've got several games that have been moved, but without the references inside steam having been updated (I had planned to update the references by telling steam to uninstall, then reinstall to the new location).

When moving a game,
1. if the folder doesn't exist, please check to see if it exists in the destination library and prompt to update steam rather than erroring out.
2. if the folder exists on both sides, show dates/sizes of the folders and prompt
   - do nothing
   - rename the destination folder and continue
   - delete the destination folder and continue
   - merge the source folder into the destination folder and continue
   - keep both folders and update steam to use the destination folder instead of the source folder

**Comment by DjScribbles** [comment]
If I'm understanding you right, your issue stems from Game Pipe's inability to handle 0Byte games where the folder associated with the game doesn't exist. 

Fixing this has been on my radar for a while, but I lost momentum on the project (but I am starting to get back into working on Game Pipe related stuff). I will try to push out a fix for this sometime this week along with some minor features I've had waiting to deploy.

**Comment by Efreak** [comment]
That's awesome. I personally solved it by just dumping all the games I never play anymore, so there's no hurry here (I had ~60 games installed just because they were 100mb or less, and another 30 or so that I never got around to playing)

It might also be nice to give Game Pipe the ability to clean out unrecognized folders. I've noticed in the past that steam sometimes seems to leave some folders behind when uninstalling games.

**Comment by DjScribbles** [comment]
This is now fixed in [release 0.1.8](https://github.com/DjScribbles/GamePipe/releases/tag/0.1.8).

I've always had a plan to implement a cleanup feature, and I've got it documented in #1 so I'm going to close this issue.
