### ISSUE TITLE
"Open Store Page" Option Fails With Google Chrome

### ISSUE THREAD

**Issue by ghost** [DjScribbles/GamePipe#2]
Conditions to reproduce issue:
-Have Google Chome installed & set as default browser for system (found in Chrome version 48.0.2564.116 m and Version 49.0.2623.75 m)
-Have Google Chrome already running
-in Game Pipe, click a game's '...' button, then click "Open Store Page".

Every time I do this on any game, I get a warning pop-up from Chrome saying "Google Chrome is unresponsive. Relaunch Now?"

This does NOT occur if Chrome isn't already running, so this implies to me that whatever you're doing to launch the game URL does not work well with Chrome on Windows.

**Comment by DjScribbles** [comment]
That's peculiar, I think this almost has to be a Chrome issue. There's no issue in firefox (my browser of choice) and the code to perform this is just using Process.Start(url); which just invokes windows to open the url in your default browser.

If you do "start www.google.com" from a command prompt do you get similar results?

**Comment by ghost** [comment]
Weirdly, now I can't reproduce the issue anymore. Not sure what the deal is, but hey, if it's not happening anymore I guess consider this one closed :P
