### ISSUE TITLE
[Possible bug] Application crashes when disk is full

### ISSUE THREAD

**Issue by r6d2** [DjScribbles/GamePipe#25]
When moving a game to a disk with not enough space, the app crashes ungracefully once it runs out of disk.

**Comment by DjScribbles** [comment]
Could you provide the log file containing this message, just so I can ensure I tackle the correct source of the exception. The log file is contained in:
<GamePipe install>\Logs\log.txt

I have some checks to ensure you don't overfill the hard-drive, but clearly they're not infallible.

**Comment by r6d2** [comment]
Unfortunately I din't keep the log. Are your checks done before each file is being copied or just before the whole game is moved?

I think you may be missing the case where other apps are writing on the same disk at the same time and winning the race. From this point of view, checking before each file and pre-allocating may give best results.

**Comment by DjScribbles** [comment]
Ok, I kinda suspected there were other applications also writing to the disk at the time, because I did add logic to handle this scenario, but I knew it was a bit rudimentary. I'll include some code in my next release to simply handle the potential IO exception when writing the file.

**Comment by DjScribbles** [comment]
With the logic just added, any IO exception on write or file close will be caught. I was able to force this failure by pausing and filling my HDD during a transfer, then resuming.

When the disk is full Game Pipe will prompt you that it is full, if you address the issue by freeing up space, then click OK, your transfer will happily resume (if you didn't make room and clicked ok, you'll just keep getting the message), if you click cancel it will abort the transfer.

(Adding a separate issue #27 for aborted transfers not deleting the left-over files, which is a possible aggravating issue in this scenario.)
