### ISSUE TITLE
[Possible bug] GamePipe_Installer_1_0_2.exe still says there's a new version available

### ISSUE THREAD

**Issue by r6d2** [DjScribbles/GamePipe#26]
Hello!

As per the subject, same thing happens using the ZIP download. I don't know if the message is incorrect or the new release does not contain the new version. (Perhaps an "about" option would help clear this up, but cannot find it.)

Cheers!

**Comment by DjScribbles** [comment]
Ah woops, looks like I screwed up the version number when I built the
realise. I'll try to correct that before the weekend is over.

As a note, I put the version number in the title bar.

Thanks again

**Comment by DjScribbles** [comment]
This is now resolved, apparently I missed the one file that mattered with my search and replace on the version number. Downloading the binaries in 1.0.2 is now fixed.
