### ISSUE TITLE
Aborted transfers don't delete the files already transferred

### ISSUE THREAD

**Issue by DjScribbles** [DjScribbles/GamePipe#27]
Add logic to delete files to "DoAbortProcess" for local and network copies.

**Comment by r6d2** [comment]
For this purpose maybe you can benefit from Steam's own "library repair" service. I've just used it directly from the Steam client, but maybe there's a CLI option or API call.

**Comment by DjScribbles** [comment]
From my testing, this feature doesn't appear to actually delete folders for games that don't have an associated ACF file, so it wouldn't resolve this. 

I wasn't aware this was something Steam offered until now, and I'm unsure what it's actually doing, though it takes a good chunk of time to complete.

**Comment by DjScribbles** [comment]
This issue is now fixed with the latest release 1.0.3
