### ISSUE TITLE
User Interface Issues

### ISSUE THREAD

**Issue by campbeb** [DjScribbles/GamePipe#7]
I am by no means a UI expert, but wanted to give you some feedback from my first time running the program.
I'm referring to this section: 
![image](https://cloud.githubusercontent.com/assets/1089399/13600076/8b81bd42-e4f4-11e5-829f-74c5f753de7a.png)
1. It is hard to tell if the buttons are enabled or disabled. It would be easier to tell if the text was brighter, like the active tab text color. 
2. All of the items are in a row with no grouping or separation. I thought I needed to do all of the things in order ( add IP, then port, then add friend, then start hosting).
3. The terminology is mixed. "Add Friend" means connect to remote host. But, start local host is "Start Hosting" not receive friend. Maybe change "Add Friend" to something like "Connect to Host", "Connect to Friend", "Connect to Remote", etc

Other feedback for that tab:
1. When I first open it, I don't know what Search is for (server or games?) Maybe it should be disabled until a remote host shows up. Or maybe move the server section to the top and the search bar down closer to game list (although, having it prominently up top is nice once servers are added)
2. Remote servers added can't be removed. Also, if you add too many, they appear off to the right, but there is no scroll bar

I like your overall design choices (big tab drag and drop) and non-standard coloring. You might want to take a look at [Material Design In XAML](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit). You can get nice looks with on-the-fly color changes very easily.

**Comment by DjScribbles** [comment]
Thanks for the feedback, I've finally gotten around to reworking this screen to address a lot of the ambiguities that you've got listed here. If you've got the time feel free to leave some feedback.
