### ISSUE TITLE
FR: Delete/move multiple games at once

### ISSUE THREAD

**Issue by skath** [DjScribbles/GamePipe#9]
Before GamePipe was around, I'd moved a lot of games manually from my big slow drive to SSD. 

I must have left some of the appmanifest files behind on the slow drive, because they show up in gamepipe as 0-byte games on the old location (in addition to showing up with proper sizes in the new location). 

There are over 50 of them and I want to clean them all up. It looks like I have to [click the menu, click delete, click yes, wait] 50 times. 

It would be nice to be able to select multiple games and delete them all.

I'm sure there are other use cases for deleting multiple games at once. Seems like it would be a handy feature.

**Comment by ghost** [comment]
This! I noticed that the UI presently honors the standard Shift+Left Click and CTRL+Left Click selection options to select multiple items. However, you're presently not able to interact with all selected items.

Might I suggest enabling the ability to right-click on selected items? This seems like the easiest way to allow operations on multiple items to be hooked into the UI?

So you can select a bunch of games, then right-click on any of them and be presented with whatever options make sense for that game.

The other thing that would need to be handled is Left-Click Drag events happening to multiple-selections.

**Comment by DjScribbles** [comment]
This will be on my list later this week or early next. I plan to fold in the multi-select capability with the existing menus, (with a more appropriate warning 'are you sure you want to delete 9 things?')

**Comment by DjScribbles** [comment]
I've now added this feature in [release 0.1.6](https://github.com/DjScribbles/GamePipe/releases/tag/0.1.6). It works with the existing multi-select feature, moving is still via drag&drop, and there's another option below the existing "Delete Game" that appears when multiple games are selected.
